'use client';

import React from 'react';
import {
  Box,
  Container,
  Heading,
  Text,
  VStack,
  useColorModeValue,
  Divider,
  Link,
} from '@chakra-ui/react';
import { useRouter } from 'next/navigation';

const TermsAndConditions = () => {
  const router = useRouter();
  const bgColor = useColorModeValue('gray.50', 'gray.900');
  const cardBg = useColorModeValue('white', 'gray.800');
  const textColor = useColorModeValue('gray.700', 'gray.300');
  const headingColor = useColorModeValue('gray.800', 'white');

  return (
    <Box minH="100vh" bg={bgColor} py={8}>
      <Container maxW="4xl">
        <Box bg={cardBg} p={8} borderRadius="lg" shadow="md">
          <VStack spacing={6} align="stretch">
            <Heading as="h1" size="xl" color={headingColor} textAlign="center">
              Terms and Conditions
            </Heading>
            
            <Text color={textColor} fontSize="lg" textAlign="center">
              {`Welcome to Verdictone Co. Ltd (the "Site"), (the "Platform"). By accessing and using the services provided by Verdictone Co. Ltd, including any tools, features, content, and/or the AI-powered legal assistant (the "AI Bot"), you agree to comply with and be bound by these Terms and Conditions (the "Agreement"). If you do not agree to these terms, please do not use the Platform.`}
            </Text>

            <Divider />

            <VStack spacing={4} align="stretch">
              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  1. Definitions
                </Heading>
                <VStack spacing={2} align="stretch">
                  <Text color={textColor}>
                    <strong>{`Verdictone Co. Ltd, "we", "us", or "our":`}</strong> Refers to the website and the company providing the Platform.
                  </Text>
                  <Text color={textColor}>
                    <strong>User or You:</strong> Refers to any individual or entity that accesses or uses the Platform.
                  </Text>
                  <Text color={textColor}>
                    <strong>AI Bot:</strong> Refers to the artificial intelligence-powered legal assistant deployed on the Platform.
                  </Text>
                  <Text color={textColor}>
                    <strong>Services:</strong> Includes all products, services, and tools provided by Verdictone Co. Ltd, including access to the AI Bot.
                  </Text>
                </VStack>
              </Box>

              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  2. Acceptance of Terms
                </Heading>
                <Text color={textColor}>
                  By using the Platform, you affirm that you have read, understood, and agreed to these Terms and Conditions, as well as our Privacy Policy. If you are using the Platform on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these terms.
                </Text>
              </Box>

              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  3. Use of the Platform
                </Heading>
                <Text color={textColor} mb={3}>
                  You agree to use the Platform in compliance with all applicable laws and regulations. You shall not:
                </Text>
                <VStack spacing={1} align="stretch" pl={4}>
                  <Text color={textColor}>• Use the Platform for any unlawful or fraudulent activity.</Text>
                  <Text color={textColor}>{`• Interfere with or disrupt the Platform's services or servers.`}</Text>
                  <Text color={textColor}>• Attempt to reverse-engineer, hack, or modify the AI Bot or any other technology underlying the Platform.</Text>
                  <Text color={textColor}>• Use the Platform in any manner that could damage, disable, overburden, or impair the Platform.</Text>
                </VStack>
              </Box>

              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  4. The AI Bot: Disclaimer of Liability
                </Heading>
                <VStack spacing={3} align="stretch">
                  <Text color={textColor}>
                    The AI Bot provided on the Platform is an automated tool powered by artificial intelligence. The AI Bot is designed to offer general legal information based on the data it has been trained on. However, Verdictone Co. Ltd does not guarantee the accuracy, reliability, or applicability of any information provided by the AI Bot. The AI Bot does not provide legal advice, nor should any information generated by the AI Bot be construed as legal counsel.
                  </Text>
                  <Text color={textColor}>
                    Verdictone Co. Ltd does not assume any responsibility or liability for any actions, decisions, or consequences resulting from the use of the AI Bot.
                  </Text>
                  <Text color={textColor}>
                    You acknowledge that the AI Bot may not always reflect current laws or regulations, and it is your responsibility to verify any legal information independently. If you require personalized legal advice, you should consult with a licensed attorney.
                  </Text>
                </VStack>
              </Box>

              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  5. Intellectual Property
                </Heading>
                <VStack spacing={3} align="stretch">
                  <Text color={textColor}>
                    All content on the Platform, including but not limited to text, graphics, logos, images, videos, and software, is owned by Verdictone Co. Ltd or its licensors and is protected by copyright, trademark, and other intellectual property laws.
                  </Text>
                  <Text color={textColor}>
                    You are granted a limited, non-exclusive, non-transferable license to access and use the Platform for personal or business purposes, subject to these Terms and Conditions.
                  </Text>
                  <Text color={textColor}>
                    You may not reproduce, distribute, or modify any content from the Platform without the prior written consent of Verdictone Co. Ltd.
                  </Text>
                </VStack>
              </Box>

              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  6. Privacy Policy
                </Heading>
                <Text color={textColor}>
                  Your use of the Platform is also governed by our Privacy Policy, which can be found on our website. By using the Platform, you consent to the collection and use of your personal data as outlined in the Privacy Policy.
                </Text>
              </Box>

              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  7. No Warranties
                </Heading>
                <VStack spacing={3} align="stretch">
                  <Text color={textColor}>
                    {`Verdictone Co. Ltd provides the Platform and the AI Bot "as is" and without any warranties, express or implied. We do not warrant that the Platform will be free from errors or interruptions, or that the AI Bot will provide accurate, reliable, or up-to-date legal information.`}
                  </Text>
                  <Text color={textColor}>
                    Verdictone Co. Ltd shall not be liable for any errors or omissions in the content provided by the AI Bot, nor for any actions taken or not taken based on such content.
                  </Text>
                </VStack>
              </Box>

              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  8. Limitation of Liability
                </Heading>
                <Text color={textColor}>
                  To the maximum extent permitted by law, Verdictone Co. Ltd and its affiliates, directors, officers, employees, agents, and contractors shall not be liable for any direct, indirect, incidental, consequential, special, or punitive damages arising from or in connection with your use of the Platform, including any use of the AI Bot. This includes but is not limited to, loss of profits, loss of data, or any other damages resulting from your reliance on any information provided by the AI Bot.
                </Text>
              </Box>

              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  9. Indemnification
                </Heading>
                <Text color={textColor}>
                  You agree to indemnify and hold harmless Verdictone Co. Ltd and its affiliates, directors, officers, employees, agents, and contractors from any claims, damages, liabilities, costs, and expenses (including reasonable legal fees) arising out of or in connection with your use of the Platform, including your use of the AI Bot, violation of these Terms and Conditions, or infringement of the rights of any third party.
                </Text>
              </Box>

              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  10. Account and Registration
                </Heading>
                <Text color={textColor} mb={3}>
                  If the Platform requires you to create an account, you agree to:
                </Text>
                <VStack spacing={1} align="stretch" pl={4}>
                  <Text color={textColor}>• Provide accurate, current, and complete information during the registration process.</Text>
                  <Text color={textColor}>• Maintain the confidentiality of your account credentials and notify us immediately if you suspect any unauthorized use of your account.</Text>
                  <Text color={textColor}>• Be responsible for all activities under your account, whether or not you have authorized such activities.</Text>
                </VStack>
              </Box>

              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  11. Termination of Access
                </Heading>
                <Text color={textColor}>
                  Verdictone Co. Ltd reserves the right to suspend or terminate your access to the Platform at any time, without notice, for any reason, including but not limited to violation of these Terms and Conditions or illegal activities.
                </Text>
              </Box>

              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  12. Third-Party Links and Content
                </Heading>
                <Text color={textColor}>
                  The Platform may contain links to third-party websites or content. These links are provided solely for your convenience, and Verdictone Co. Ltd is not responsible for the accuracy, legality, or appropriateness of the content on these third-party sites.
                </Text>
              </Box>

              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  14. Governing Law and Dispute Resolution
                </Heading>
                <Text color={textColor}>
                  These Terms and Conditions shall be governed by and construed in accordance with the laws of the Federation of Nigeria. Any dispute arising from these Terms and Conditions or your use of the Platform shall be resolved through Arbitration/Mediation in accordance with the Laws of Nigeria except where prohibited by law.
                </Text>
              </Box>

              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  15. Changes to Terms and Conditions
                </Heading>
                <Text color={textColor}>
                  Verdictone Co. Ltd reserves the right to update or modify these Terms and Conditions at any time without prior notice. Any changes will be posted on this page, and the updated terms will take effect immediately upon posting. Your continued use of the Platform after such changes constitutes your acceptance of the revised terms.
                </Text>
              </Box>

              <Box>
                <Heading as="h2" size="lg" color={headingColor} mb={3}>
                  16. Contact Information
                </Heading>
                <Text color={textColor}>
                  If you have any questions or concerns about these Terms and Conditions, please contact us at:
                </Text>
                <Text color={textColor} mt={2}>
                  <strong>Email:</strong> <Link href="mailto:Olamide@djetlawyer.com" color="blue.500">Olamide@djetlawyer.com</Link>
                </Text>
              </Box>

              <Divider />

              <Box bg={useColorModeValue('blue.50', 'blue.900')} p={4} borderRadius="md">
                <Text color={textColor} fontWeight="bold" textAlign="center">
                  By accessing and using Verdictone Co. Ltd, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions.
                </Text>
              </Box>
            </VStack>
          </VStack>
        </Box>
      </Container>
    </Box>
  );
};

export default TermsAndConditions; 